language: perl

perl:
  - "5.16"

addons:
  postgresql: "9.3"

env:
  global:
    - secure: ZYRGAGHl/9mtiuNtSPhRR34RAqQTX5qMthUO07dytNtle7EPJ+K9tNwT6RvTL6qsNxE0gtvNiAGIZP8aKo/wzEdHKMeJT7E3HaVw/7OQpd/qHegxJlLrkTbo1DlZISM0UgM1u6505ioxzKFed+YaPq+EveHT5V713qkH626GUOw=
    - PGVERSION="9.3"
    - DNAP_UTILITIES_VERSION="0.5.1"
    - JANSSON_VERSION="2.7"
    - BATON_VERSION="0.16.3"
    - CK_DEFAULT_TIMEOUT=20
    - IRODS_VAULT=/usr/local/var/lib/irods/Vault
    - PLATFORM=ubuntu12
    - ARCH=x86_64
    - RENCI_URL=ftp://ftp.renci.org
    - WTSI_NPG_URL=https://github.com/wtsi-npg/irods
    - PG_PLUGIN_VERSION=1.8
  matrix:
    - IRODS_VERSION=3.3.1
    - IRODS_VERSION=4.1.8

before_install:
  # workaround for iRODS buffer overflow
  # see https://github.com/travis-ci/travis-ci/issues/5227
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts # optionally check the content *after*
  - ./scripts/travis_before_install.sh

install:
  - ./scripts/travis_install.sh

before_script:
  - source ./scripts/travis_before_script.sh
  - ienv
  - ilsresc -l
  - ils

script:
  - ./scripts/travis_script.sh

after_script:
  - ./scripts/travis_after_script.sh

after_success:
  - ./Build dist
  - export DIST_FILE=$(ls WTSI-NPG-iRODS-*.tar.gz)
  - export SHA256_FILE=$DIST_FILE.sha256
  - shasum -a 256 $DIST_FILE > $SHA256_FILE

deploy:
  provider: releases
  api-key: $GH_OAUTH
  file:
    - $DIST_FILE
    - $SHA256_FILE
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
