dist: bionic

sudo: required

addons:
  apt:
    packages:
      - rabbitmq-server

services:
  - docker
  - postgresql
  - rabbitmq

language: perl

perl:
  - "5.26"

env:
  global:
    - WSI_NPG_GITHUB_URL=https://github.com/wtsi-npg
    - WSI_CONDA_CHANNEL=https://dnap.cog.sanger.ac.uk/npg/conda/devel/generic/
    - NPG_RMQ_CONFIG='./etc/rmq_travis_config.json'
    - NPG_RMQ_HOST='localhost'
  matrix:
    - DOCKER_IMAGE="wsinpg/ub-16.04-irods-4.2:latest" IRODS_VERSION="==4.2.7"  BATON_VERSION=">2.0.1"
    - DOCKER_IMAGE="wsinpg/ub-12.04-irods-4.1:latest" IRODS_VERSION="==4.1.12" BATON_VERSION="==2.0.1"

matrix:
  allow_failures:
    - env: DOCKER_IMAGE=wsinpg/ub-16.04-irods-4.2:latest

before_install:
  - docker pull "$DOCKER_IMAGE"
  - docker run -d -p 1247:1247 "$DOCKER_IMAGE"
  - docker ps -a
  - ./scripts/travis_before_install.sh

install:
  - ./scripts/travis_install.sh

before_script:
  - ./scripts/rabbitmq_config.sh

script:
  - ./scripts/travis_script.sh
